---
Name: bootstrap-config
After:
    - '*'
---
GDBackend:
  default_quality: 90
SilverStripe\Assets\Flysystem\AssetAdapter:
  file_permissions:
    'file':
      'public': '0644'
      'private': '0600'
SilverStripe\Assets\InterventionBackend:
  flush_enabled: false
